version: "3"
services:
  node-app:
    container_name: lms_node-app_api
    restart: always
    build:
      context: .
      target: production
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    container_name: lms_mysql_database
    image: mysql:8.0
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: <username>
    ports:
      - 3306:3306
    networks:
      - app-network
volumes:
  node-app_volume:
  mysql_volume:
networks:
  app-network:
    driver: bridge
