version: "3"
services:
  nodeapp:
    container_name: lms-nodeapp
    hostname: nodeapp
    # restart: always
    build:
      context: .
      target: development
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://fadliarz:rootpassword@postgresql:5432/lms?connection_limit=9
      PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - lms-network
  postgres:
    container_name: lms-postgresql
    hostname: postgresql
    image: postgres:16.1-alpine
    # restart: always
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: fadliarz
      POSTGRES_USERNAME: fadliarz
      POSTGRES_PASSWORD: rootpassword
    ports:
      - 5432:5432
    networks:
      - lms-network
networks:
  lms-network:
    driver: bridge